# Generated by Django 3.2.12 on 2022-06-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('data_atual', models.DateTimeField(auto_now=True)),
                ('tkm_d', models.DecimalField(decimal_places=3, max_digits=8)),
                ('parada_d', models.IntegerField()),
                ('kmep_d', models.DecimalField(decimal_places=3, max_digits=8)),
                ('tkm_acum', models.IntegerField()),
                ('parada_acum', models.IntegerField()),
                ('kmep_acum', models.DecimalField(decimal_places=3, max_digits=8)),
                ('tipo_kmep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_kmep', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ciclo',
                'verbose_name_plural': 'ciclos',
            },
        ),
    ]
